### ISSUE TITLE
Add tags to preserve backward compatibility

### ISSUE THREAD

**Issue by therealmikz** [JCook21/ReactAMQP#3]
PR #2 is not backwards compatible, it will force people to update dependencies.
According to this you should add a tag (f. ex. 0.1) on commit a07a4ad410bd8da7a9c1e69a39cc4dd855bec1d9 to preserve compatibility with react/event-loop 0.2.\* to not force people to update their dependencies and 0.2.0 on b501ba7b53a45303823976c9105a926825680454 to allow people use new version not by providing "dev-master".

**Comment by ZhukV** [comment]
+1. Please create the initial tag `v1.0.0`. After this developer can fix the version in own libraries/projects.

Thank.

**Comment by JCook21** [comment]
@ZhukV as the first line of the README on this repo says, this project is no longer maintained. If you'd like to offer a PR for this I'd be happy to consider it but I'm not maintaining this.
